# docker-compose.yml
version: '3.3'

services:
  rest-service:
    build: ./rest
    ports:
      - 80:8080
    depends_on:
      - rest-db
    networks:
      - webservice

  rest-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - rest_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "gwp"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - webservice

volumes:
  rest_db_data: {}

networks:
  webservice:
    external: true

